
services:
  api:
    build: .
    container_name: event_analytics_api
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app
    command: >
      sh -c "
      alembic upgrade head &&
      uvicorn app.main:app --host 0.0.0.0 --port 8000
      "

  db:
    image: postgres:15
    container_name: event_analytics_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: event_analytics
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
  
  tests:
    build: .
    container_name: event_analytics_tests
    env_file:
      - .env
    depends_on:
      - db
    command: pytest -q
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@db:5432/event_analytics_test

volumes:
  postgres_data:
